### ISSUE TITLE
Products not displaying

### ISSUE THREAD

**Issue by ankitluthra** [MrRDJack/ACRA-iOS#1]
Just added a few print statements, but no idea what happened now it's not showing any products on  the product page. It was working perfectly fine yesterday. Nothing changed since then. Let me know if any one figures out what the issue is.

**Comment by TessHuelskamp** [comment]
Are you working on the latest version of the repo? I reverted back to a previous commit to get the pictures working this morning but thought that I had done that in a different repo. What does `git status` say?

**Comment by ankitluthra** [comment]
On branch master
Your branch is up-to-date with 'origin/master'.
You are currently reverting commit c19776f.
  (all conflicts fixed: run "git revert --continue")
  (use "git revert --abort" to cancel the revert operation)

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	ACRA-iOS/ACRA-iOS.xcodeproj/project.xcworkspace/xcuserdata/cse498.xcuserdatad/
	ACRA-iOS/ACRA-iOS.xcodeproj/xcuserdata/cse498.xcuserdatad/
	ACRA-iOS/ACRA-iOS.xcworkspace/

nothing added to commit but untracked files present (use "git add" to track)

**Comment by ankitluthra** [comment]
On branch master
Your branch is up-to-date with 'origin/master'.
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	ACRA-iOS/ACRA-iOS.xcodeproj/project.xcworkspace/xcuserdata/cse498.xcuserdatad/
	ACRA-iOS/ACRA-iOS.xcodeproj/xcuserdata/cse498.xcuserdatad/
	ACRA-iOS/ACRA-iOS.xcworkspace/

nothing added to commit but untracked files present (use "git add" to track)

**Comment by TessHuelskamp** [comment]
Looking like AWS is down so its not something we did. I'm closing this since I'm asssuming things will be fixed when the internet is working again. 

It's worth asking Dave and Anand what would be good to do about this. This event seems extremely rare but am curious what their thoughts are. 

Looks like the dog is the correct thing to display there. We should maybe have different errors depending on what the API returns.
